### ISSUE TITLE
can't mock com.microsoft.azure.cosmosdb.ResourceResponse as it's final class

### ISSUE THREAD

**Issue by rgampa** [Azure/azure-cosmosdb-java#138]
Getting below error when mocking ResourceResponse, using sdk `version 2.4.5`. I saw FeedResponse doesn't have final keyword, can you make it same for ResourceResponse? 

```
FAILED CONFIGURATION: @BeforeMethod setup
org.mockito.exceptions.base.MockitoException: 
Cannot mock/spy class com.microsoft.azure.cosmosdb.ResourceResponse
Mockito cannot mock/spy because :
 - final class
```

**Comment by rgampa** [comment]
Found workaround to mock final class here: https://www.baeldung.com/mockito-final. However it will be nice if final is removed from classes where consumer have to mock for unit testing.

**Comment by christopheranderson** [comment]
Done in V3

**Comment by christopinka-vp** [comment]
Actually, I don't think you want to remove final for testing purpose only. See: https://ocramius.github.io/blog/when-to-declare-classes-final/
