### ISSUE TITLE
RntbdRequestManager.channelUnregistered must complete pending requests exceptionally

### ISSUE THREAD

**Issue by David-Noble-at-work** [Azure/azure-cosmosdb-java#163]
**ISSUE:**
When a connection is reset (closed) by a peer the Netty framework shuts down the channel with a `ChannelClosedException`, skipping calls to `RntbdRequestManger.exceptionCaught` and `RntbdRequestManager.close`. Consequently, pending requests, if any, are not released and `RntbdRequestManger.channelUnregistered` throws an `IllegalStateException`.

**RESOLUTION:**
`RntbdRequestManager.channelUnregistered` should 
* call `RntbdRequestManager.completeAllPendingRequestsExceptionally` to ensure that all pending requests are released and
* not throw an `IllegalStateException`

**Comment by anandvarkeyphilips** [comment]
Is this fixed and released already?
I got an error with message: closed exceptionally with 1 pending requests
