### ISSUE TITLE
Difference between azure-documentdb and azure-cosmosdb sdk

### ISSUE THREAD

**Issue by sophiaso** [Azure/azure-cosmosdb-java#23]
Hi, what's the difference between this repo and [previous azure-documentdb-java](https://github.com/Azure/azure-documentdb-java)? Is it recommended to use this new repo as reference?

Will the `azure-documentdb` be updated and released in the future?
For the previous documentdb users, better to switch from `azure-documentdb` to `azure-cosmosdb ` ?

**Comment by moderakh** [comment]
@sophiaso Both this github and the previous provide Java SDK for SQL api of Azure Cosmos DB.

The difference is this repo provides Async API with non blocking IO, however the previous on only provides sync API with blocking IO.

We will maintain both SDKs. But if you have a requirement for using async API you can consider using this new SDK.

**Comment by christopheranderson** [comment]
Closing old issues
