### ISSUE TITLE
Add support of getDuration for Queries in Cosmos Diagnostics - V4 Java Cosmos SDK 

### ISSUE THREAD

**Issue by manishmsfte** [Azure/azure-cosmosdb-java#364]
getDuration is part of Cosmos Diagnostics and provide latency information but it doesn't work for queries. Customers needed it in on priority.

**Comment by kushagraThapar** [comment]
@manishmsfte - azure-cosmos V4 Java SDK has been relocated here : https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-cosmos
This issue is a duplicate of this feature issue which is in our backlog, please follow it here: https://github.com/Azure/azure-sdk-for-java/issues/12911
