### ISSUE TITLE
Configure check style in the project 

### ISSUE THREAD

**Issue by otaviojava** [Azure/azure-cosmosdb-java#42]
Does make sense a PR with check style in the project?

This way, the project will easier to more person contribute and also to maintain the project, I believe that we could start with:

* number of characts in a line
* standard to Java class and method
* Make the header license mandatory
* Unused imports

Ref: http://checkstyle.sourceforge.net/

**Comment by moderakh** [comment]
@otaviojava thanks. This was one of the things that we had in our backlog queue, we haven't got into doing it yet.

It would help to have some validation on checkstyle integrated in the maven pom file.
We should start with maven code style integration without doing any code change to actual existing java files.

In your opinion, for which maven build phase this should be configured?

**Comment by otaviojava** [comment]
Ok, I'll open a PR soon

**Comment by christopheranderson** [comment]
Closing old issues. (Still a good idea!)
