### ISSUE TITLE
Issue for non-english locales

### ISSUE THREAD

**Issue by fpaparoni** [Azure/azure-cosmosdb-java#51]
Computers running on non-English locales may run in to a  

**com.microsoft.azure.cosmosdb.DocumentClientException: The input date header is invalid format. Please pass in RFC 1123 style date format.**

Setting a locale

`Locale.setDefault(Locale.US);`

solves the problem. This is like [another issue](https://github.com/Azure/azure-documentdb-java/pull/10) in a related library

**Comment by moderakh** [comment]
thanks for reporting this.
Would you be interested in sending a PR for fixing this?

**Comment by fpaparoni** [comment]
I created a PR #52 for this

**Comment by moderakh** [comment]
Thanks @fpaparoni.
I merged the PR. It will be in the next release.

I leave this issue open till we do a release.

**Comment by moderakh** [comment]
fixed in 2.0.1 release which got published to maven minutes ago.
