### ISSUE TITLE
How to partition the query to different physical partitions.

### ISSUE THREAD

**Issue by zhouchong90** [Azure/azure-cosmosdb-java#57]
Hi,

I'm trying to execute a very large query that needs to return millions of records, so I want to partition the query and use multiple machines to process the results.

My logical partition key would be a UUID of a document, so that will not be very helpful for me to allocate different parts to each worker node. Can I get the physical partition ID and execute my query only within a particular physical partition?

Here's what I have tried:

FeedOptions feedOptions = new FeedOptions();
        feedOptions.setEnableCrossPartitionQuery(false);
        feedOptions.setPartitionKeyRangeIdInternal("0");

client.queryDocuments(collectionPath, "SELECT * FROM  e where e.docType = 'address'", feedOptions)
                .flatMapIterable(FeedResponse::getResults);

But changing the partitionKeyRangeId doesn't seem to change the results at all.

Please advise.

**Comment by moderakh** [comment]
@zhouchong90 which version of the SDK are you using?

**Comment by zhouchong90** [comment]
I'm currently using 1.0.0. Is there a new feature in the latest version that changes this?

**Comment by moderakh** [comment]
@zhouchong90 you are on a very old version. We are doing active development and bugfixes and this issue has been fixed a while back. As of now the latest version is 2.0.1.
