### ISSUE TITLE
Any plans to support query metrics

### ISSUE THREAD

**Issue by chetanmeh** [Azure/azure-cosmosdb-java#66]
CosmosDB supports providing [query metrics][1] via `x-ms-documentdb-populatequerymetrics` header. Are there any plans to support this header in this sdk?

[1]: https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sql-query-metrics

**Comment by moderakh** [comment]
@chetanmeh yes this is in our backlog.

**Comment by moderakh** [comment]
2.4.0 has support for QueryMetrics.

**Comment by chetanmeh** [comment]
Thanks @moderakh for adding this support!. Would make use of it now

**Comment by chetanmeh** [comment]
Gave metrics a try today (apache/incubator-openwhisk#4275) and found it be very informative. Thanks for the pretty report to make sense of the stats :tada:
