### ISSUE TITLE
Upgrade RxJava version to 2.x

### ISSUE THREAD

**Issue by Incarnation-p-lee** [Azure/azure-cosmosdb-java#69]
As RxJava went to EOF, is there any plan this package will upgrade to RxJava 2.x ? Below is from RxJava README.

__As of March 31, 2018, The RxJava 1.x branch and version is end-of-life (EOL). No further development, bugfixes, documentation changes, PRs, releases or maintenance will be performed by the project on the 1.x line.__

**Comment by moderakh** [comment]
Hi @Incarnation-p-lee we are planning an upgrade to RxJava2. That is planned for early 2019.
this is a duplicate of https://github.com/Azure/azure-cosmosdb-java/issues/28

**Comment by Incarnation-p-lee** [comment]
@moderakh 
Sorry for missing the existed one. So I will close this issue and track the status from #28
