### ISSUE TITLE
Support for MongoDB API

### ISSUE THREAD

**Issue by ArturSkowronski** [Azure/azure-cosmosdb-java#72]
Hello. Are there any plans to support MongoDB API with Reactive access? 

We are currently using **mongodb-driver-async** and we are wondering if it will work reliably with CosmosDB or do you plan first party support in **azure-cosmosdb-java**.

**Comment by moderakh** [comment]
@ArturSkowronski this repo provides SQL API for CosmosDB. 

Seems MongoDB has a driver with RX support: https://mongodb.github.io/mongo-java-driver-rx/
If you have questions on CosmosDB support for MongoDB API, please out to "askcosmosdb at microsoft.com"

I am closing the issue here.
