### ISSUE TITLE
Support for Netty 4.1.32

### ISSUE THREAD

**Issue by chetanmeh** [Azure/azure-cosmosdb-java#79]
Currently SDK has dependency on Netty v 4.1.22 (released 21-Feb-2018). Would it be fine to use Netty v 4.1.32 (released 29-Nov-2018)? We plan to make use of some other  thirdparty library which uses the newer version. So need to  move to newer version.

**Comment by moderakh** [comment]
@chetanmeh we haven't tested the SDK with the version of netty you mentioned.
However I would expect it to work without any problem. Please give it a try if you face any problem let us know we will help.

**Comment by moderakh** [comment]
v2.4.0 updated to the latest netty version.
