### ISSUE TITLE
Prefer Direct mode over Gateway

### ISSUE THREAD

**Issue by chetanmeh** [Azure/azure-cosmosdb-java#84]
With 2.4 release its mentioned that Direct mode access is supported now. [Per docs][1] its mentioned that Direct mode if supported by SDK should be preferred over gateway mode.

Wanted to check if its fine to always enable direct mode now or there are some other aspects pne need to consider before enabling this mode

[1]: https://docs.microsoft.com/en-us/azure/cosmos-db/performance-tips#networking

**Comment by moderakh** [comment]
@chetanmeh go with direct mode. if you face any issue we are here to help. :-)

**Comment by christopheranderson** [comment]
In the next major version of the SDK, we'll be making Direct mode on by default (with opt-in to use Gateway mode instead).

**Comment by christopheranderson** [comment]
Done in V3
