### ISSUE TITLE
[Question]: Is cosmosdb indexing policy deprecated automatic configuration

### ISSUE THREAD

**Issue by Incarnation-p-lee** [Azure/azure-cosmosdb-java#87]
In previous, there seems to be one configuration under indexing mode, like automatic = true/false. But recently I cannot find any documentation under [here](https://docs.microsoft.com/en-us/azure/cosmos-db/index-overview).

I wonder if service side deprecated this ?

**Comment by bchong95** [comment]
Yes the field has been depreciated. By default it's set to true now.

**Comment by Incarnation-p-lee** [comment]
Thanks @bchong95
