### ISSUE TITLE
Support for LINQ operators / Pagination

### ISSUE THREAD

**Issue by spreddy2714** [Azure/azure-cosmosdb-java#90]
Hi,

We have application that requires pagination, Searching through internet found the below reference.
https://azure.microsoft.com/en-us/updates/documentdb-paging-with-top-and-new-linq-operators/

However, reading further revealed that LINQ is specific for .NET programming model. 
Can you please suggest if it is possible with java sdk(I searched all methods on client, but couldn't find any).
Or What is the best solution for pagination on 3000+ records(with approximately 50 as page size)

**Comment by christopheranderson** [comment]
LINQ support is not something we can provide since it doesn't exist in Java.

For pagination, this is supported since 2.4.3 for non-Order By queries - just grab the continuation token off of the FeedResponse. We expect to support order by queries in the next 1-2 weeks.

**Comment by christopheranderson** [comment]
opened #92 to track the last bit of this. Closing.
