### ISSUE TITLE
Order By with Continuation Tokens

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-cosmosdb-java#92]
2.4.3 added Continuation Token support for Cross Partition Queries for everything but Order By.

This is in progress and we'll close this issue once we've added this last bit of support.

**Comment by spreddy2714** [comment]
continuation token usage for pagination is fine for sequential reads.
However, If I want to read 7th page(size-10) of 100 records, I wouldn't be forced to read prior 6 pages just to hold onto the token. Is there any alternate way, where I can pick intermediate batch of records, without reading prior ones?

**Comment by christopheranderson** [comment]
This will be released with 2.5.0 (should be up this weekend).
